# Perfil: dev (Development)
# Este archivo contiene overrides para un despliegue en development.
# Principales cambios vs application.yaml:
# - PostgreSQL como datasource por defecto (configurable por variables de entorno)
# - Flyway habilitado para migraciones
# - jpa.hibernate.ddl-auto=validate (Flyway maneja el schema)

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    # Usa variables de entorno o valores por defecto razonables
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:springboot_course}}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: SpringbootCoursePool-Dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 25
          fetch_size: 50
        order_inserts: true
        order_updates: true
        query:
          in_clause_parameter_padding: true
        generate_statistics: true
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: build/generated-schema.sql
              create-source: metadata
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-migration-naming: true
    out-of-order: false
    clean-disabled: true
    validate-on-migrate: true

  docker:
    compose:
      enabled: true
      file: docker-compose.yml
      lifecycle-management: start_and_stop

  h2:
    console:
      enabled: false

server:
  port: ${PORT:8080}

logging:
  level:
    org.flywaydb: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.stat: DEBUG