name:  Chore/Maintenance
description: Tareas de mantenimiento, configuraci贸n, CI/CD, refactor sin cambio funcional
title: "[CHORE] "
labels: ["chore", "maintenance"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Tarea de mantenimiento
        Describe la tarea t茅cnica que no a帽ade funcionalidad ni corrige bugs.

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n
      description: Explica qu茅 se va a hacer y por qu茅.
      placeholder: |
        Actualizar dependencias de Spring Boot 3.5.6 a 3.5.7 para parche de seguridad.
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Tipo de tarea
      options:
        - Actualizaci贸n de dependencias
        - Configuraci贸n CI/CD
        - Refactor (sin cambio funcional)
        - Mejora de tests
        - Documentaci贸n t茅cnica
        - Configuraci贸n de herramientas (lint, format)
        - Optimizaci贸n de build
        - Limpieza de c贸digo (dead code, warnings)
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceptaci贸n
      placeholder: |
        - [ ] Dependencias actualizadas en build.gradle.kts
        - [ ] Tests pasan sin cambios
        - [ ] Build exitoso en CI
        - [ ] CHANGELOG actualizado
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      options:
        -  Alta (seguridad, bloquea desarrollo)
        -  Media (mejora importante)
        -  Baja (nice to have)
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notas adicionales
      description: Impacto, riesgos, breaking changes potenciales.
    validations:
      required: false
