name:  Documentation
description: Mejoras o correcciones en documentaci贸n (Wiki, README, KDoc, OpenAPI)
title: "[DOCS] "
labels: ["documentation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Documentaci贸n
        Describe qu茅 documentaci贸n necesita crearse o actualizarse.

  - type: textarea
    id: description
    attributes:
      label: Descripci贸n
      description: Explica qu茅 falta o qu茅 hay que corregir.
      placeholder: |
        Actualizar Wiki con gu铆a de despliegue Docker y docker-compose.
    validations:
      required: true

  - type: dropdown
    id: doc-type
    attributes:
      label: Tipo de documentaci贸n
      multiple: true
      options:
        - README.md
        - Wiki (GitHub)
        - KDoc (c贸digo)
        - OpenAPI/Swagger
        - CHANGELOG.md
        - Diagramas de arquitectura
        - Gu铆as de desarrollo
        - FAQ
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceptaci贸n
      placeholder: |
        - [ ] P谩gina de Wiki creada con ejemplos
        - [ ] Enlaces verificados
        - [ ] Capturas de pantalla actualizadas
    validations:
      required: true

  - type: textarea
    id: related
    attributes:
      label: Issues/PRs relacionados
      description: Enlaza issues o PRs que requieren esta documentaci贸n.
    validations:
      required: false
