create table example_entity (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        description TEXT,
        name varchar(255) not null,
        primary key (id)
    );