config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false

comments:
  active: true
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false

complexity:
  active: true
  ComplexCondition:
    active: true
  ComplexInterface:
    active: false
  LongParameterList:
    active: true
  LongMethod:
    active: true
  LargeClass:
    active: true
  NestedBlockDepth:
    active: true
  LabeledExpression:
    active: false

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - ArrayIndexOutOfBoundsException
      - Error
      - Exception
      - IllegalMonitorStateException
      - NullPointerException
      - IndexOutOfBoundsException
      - RuntimeException
      - Throwable
    allowedExceptionNameRegex: "_|(ignore|expected).*"
  SwallowedException:
    active: false

naming:
  active: true
  ClassNaming:
    active: true
  ConstructorParameterNaming:
    active: false
  FunctionNaming:
    active: true
  PackageNaming:
    active: true
  TopLevelPropertyNaming:
    active: true
  VariableNaming:
    active: true

performance:
  active: true
  SpreadOperator:
    active: false

potential-bugs:
  active: true

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers:
      - "-1"
      - "0"
      - "1"
      - "2"
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreEnums: true
    ignoreRanges: true
    ignoreExtensionFunctions: true
  MaxLineLength:
    active: true
    maxLineLength: 160
    excludeCommentStatements: true
  ReturnCount:
    active: true
    max: 3
    excludedFunctions:
      - equals
  ForbiddenAnnotation:
    active: false
